apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-service
  namespace: streamflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alert-service
  template:
    metadata:
      labels:
        app: alert-service
    spec:
      containers:
        - name: alert-service
          image: localhost/streamflow/alert-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8004
          envFrom:
            - secretRef:
                name: vertica-secret
          env:
            - name: LATENCY_THRESHOLD
              value: "100"
            - name: PACKET_LOSS_THRESHOLD
              value: "5"
            - name: SIGNAL_THRESHOLD
              value: "-90"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
