apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulator
  namespace: streamflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simulator
  template:
    metadata:
      labels:
        app: simulator
    spec:
      containers:
        - name: simulator
          image: localhost/streamflow/simulator:latest
          imagePullPolicy: Never
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
            - name: KAFKA_TOPIC
              value: "network.events"
            - name: EVENTS_PER_SECOND
              value: "10"
            - name: NUM_TOWERS
              value: "100"
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: ANOMALY_PROBABILITY
              value: "0.15"
            - name: ANOMALY_DURATION_SECONDS
              value: "20"
            - name: HIGH_LATENCY_MAX
              value: "300"
            - name: HIGH_PACKET_LOSS_MAX
              value: "15"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
